### ISSUE TITLE
An item with the same key has already been added. Key: commerce

### ISSUE THREAD

**Issue by TekEx** [Kooboo/Kooboo#171]
Hi @koobooteam ,

Facing an issue with the log below after I tried to connect external MySQL and MS SQL Server DB. Kindly advice.

2020-12-16 18:34:01.179Z  System.TypeInitializationException: The type initializer for 'KScript.k' threw an exception.
 ---> System.ArgumentException: An item with the same key has already been added. Key: commerce
   at System.Collections.Generic.Dictionary`2.TryInsert(TKey key, TValue value, InsertionBehavior behavior)
   at Kooboo.Sites.Scripting.ExtensionContainer.get_List()
   at KScript.k..cctor()
   --- End of inner exception stack trace ---
   at KScript.k.get_SqlServer()
   at SqlEx.Module.code.SqlServer.SqlServerApi.GetDatabase(ApiCall call)
   at SqlEx.Module.code.RelationalDatabase.RelationalDatabaseApi`1.Tables(ApiCall call)
   at lambda_method2279(Closure , Object , Object[] )
   at Kooboo.Api.ApiManager.ExecuteMethod(ApiCall call, ApiMethod apimethod)
   at Kooboo.Api.ApiManager.Execute(ApiCall call, IApiProvider apiProvider) line number: 0

**Comment by koobooteam** [comment]
We probably need more information in order to check for the issue. 

Are you able to:
1. Export the site. 
2. Backup the MSSQL database. 

We use external database a lot without much trouble. We also need to know which click or link to generate the error. 

Send us the files here or to my email address. We will look into it. 

This probably is a bug.

**Comment by Smilefounder** [comment]
Hi @koobooteam , @TekEx ,

I faced the same issue on Ubuntu. And I fixed the issue with https://github.com/Kooboo/Kooboo/pull/172 here.

Cheers!
